from collections import namedtuple

HEADER_NUMBER_BYTES=4
MESSAGE_VALID_VERSION = 1

PACKET_MAX_SIZE = 64 * 1024
HEADER_MAX_SIZE = 40 * 1024

# Message types
MESSAGE_CONF = 0
MESSAGE_NON_CONF = 1
MESSAGE_ACK = 2
MESSAGE_RST = 3

# Message classes
MESSAGE_CLASS_METHOD = 0
MESSAGE_CLASS_SUCCESS = 2
MESSAGE_CLASS_CLIENT_ERROR = 4
MESSAGE_CLASS_SERVER_ERROR = 5
MESSAGE_CLASS_RESERVED = (1, 6, 7)

# Method codes
MESSAGE_CODE_EMPTY = 0
MESSAGE_CODE_GET = 1
MESSAGE_CODE_POST = 2
MESSAGE_CODE_DELETE = 4

# Request statuses
CONFIRMABLE_PACKET_NACK = "NACK"
PACKET_READY = "READY"

# UI Events
ALL_FILES = "allFiles"
FILE = "file"
NEW_FILE = "newFile"
NEW_FOLDER = "newFolder"
SAVE_FILE = "saveFile"
MOVE_FILE = "moveFile"
DELETE_FILE = "deleteFile"

HEADER_VER_FIELD_KEY = "VER"
HEADER_TYPE_FIELD_KEY = "TYPE"
HEADER_TOKEN_LENGTH_FIELD_KEY = "TOKEN_LENGTH"
HEADER_CLASS_STATUS_CODE_FIELD_KEY = "CLASS_STATUS_CODE"
HEADER_DETAIL_STATUS_CODE_FIELD_KEY = "DETAIL_STATUS_CODE"
HEADER_MESSAGE_ID_FIELD_KEY = "MESSAGE_ID"
HEADER_TOKEN_FIELD_KEY = "TOKEN"
HEADER_OPTIONS_FIELD_KEY = "OPTIONS"
HEADER_PAYLOAD_FIELD_KEY = "PAYLOAD"

PAYLOAD_PADDING_VALUE = 0xFF

HeaderField = namedtuple("HeaderField", "key length")

HEADER_VER_FIELD = HeaderField(HEADER_VER_FIELD_KEY, 2)
HEADER_TYPE_FIELD = HeaderField(HEADER_TYPE_FIELD_KEY, 2)
HEADER_TOKEN_LENGTH_FIELD = HeaderField(HEADER_TOKEN_LENGTH_FIELD_KEY, 4)
HEADER_CLASS_STATUS_CODE_FIELD = HeaderField(HEADER_CLASS_STATUS_CODE_FIELD_KEY, 3)
HEADER_DETAIL_STATUS_CODE_FIELD = HeaderField(HEADER_DETAIL_STATUS_CODE_FIELD_KEY, 5)
HEADER_MESSAGE_ID_FIELD = HeaderField(HEADER_MESSAGE_ID_FIELD_KEY, 16)
HEADER_TOKEN_FIELD = HeaderField(HEADER_TOKEN_FIELD_KEY, 32)
HEADER_OPTIONS_FIELD = HeaderField(HEADER_OPTIONS_FIELD_KEY, 32)
HEADER_PAYLOAD_FIELD = HeaderField(HEADER_PAYLOAD_FIELD_KEY, HEADER_MAX_SIZE - 96)

HEADER_CONTENT = [HEADER_VER_FIELD_KEY, HEADER_TYPE_FIELD_KEY, HEADER_TOKEN_LENGTH_FIELD_KEY,
                  HEADER_CLASS_STATUS_CODE_FIELD_KEY,HEADER_DETAIL_STATUS_CODE_FIELD_KEY, HEADER_MESSAGE_ID_FIELD_KEY, HEADER_TOKEN_FIELD_KEY,
                  HEADER_OPTIONS_FIELD_KEY, HEADER_PAYLOAD_FIELD_KEY]

HEADER_FIELDS = [HEADER_VER_FIELD, HEADER_TYPE_FIELD, HEADER_TOKEN_LENGTH_FIELD,
                 HEADER_CLASS_STATUS_CODE_FIELD,HEADER_DETAIL_STATUS_CODE_FIELD, HEADER_MESSAGE_ID_FIELD, HEADER_TOKEN_FIELD,
                 HEADER_OPTIONS_FIELD, HEADER_PAYLOAD_FIELD]

HEADER_FIELD_LENGTH_MAPPINGS = dict(HEADER_FIELDS)
